language: python
python:
  - 3.6
before_install:
  - python --version
  - pip install -U pip
  - pip install codecov
script:
  - coverage run --source=com/Guilherme/ -m unittest discovery;coverage report -m
<<<<<<< HEAD
  - python -m unittest discover
=======
  - python -m unittest discover

>>>>>>> 6e8dffb47adddebe120e5fa009d09687b049656d
